README.md
call_template_data.go
call_template_data_test.go
requester.go
testdata/config.json

Data and metadata can specify [template actions](https://golang.org/pkg/text/template/) that will be parsed and evaluated at every request. Each request gets a new instance of the data. The available variables / actions are:
```go
// call template data
type callTemplateData struct {
RequestNumber      int64  // unique incrememnted request number for each request
FullyQualifiedName string // fully-qualified name of the method call
MethodName         string // shorter call method name
ServiceName        string // the service name
InputName          string // name of the input message type
OutputName         string // name of the output message type
IsClientStreaming  bool   // whether this call is client streaming
IsServerStreaming  bool   // whether this call is server streaming
Timestamp …
```

Add support for call template data. Addresses #20.

---

cmd/ghz/main.go
config/config.go
requester.go

If you want to use your systems default root certificate without specifying the filename with `cert` you can use `grpc.WithTransportCredentials(credentials.NewClientTLSFromCert(nil, ""))`. This pull request defaults to use this option with the ability to specify a non TLS connection with `-insecure` flag.

Default to secure connection with option to use insecure flag

---

README.md

because "n" and "c" options is duplicated.

Remove duplicated options from README.md

---

config/config.go

I found an unused method at config.go.
@bojand please review 🙏

Remove unused parseConfigString from config.go

---

README.md
cmd/ghz/config.go
cmd/ghz/main.go
runner/options.go
runner/options_test.go
runner/requester.go
runner/run_test.go
web/todo.md
www/docs/example_config.md
www/docs/options.md
www/docs/usage.md

Should address #55.
All security related options:
```
-cacert		File containing trusted root certificates for verifying the server.
-cert		File containing client certificate (public key), to present to the server. Must also provide -key option.
-key 		File containing client private key, to present to the server. Must also provide -cert option.
-cname		Server name override when validating TLS certificate - useful for self signed certs.
-skipTLS	Skip TLS client verification of the server's certificate chain and host name.
-insecure	Use plaintext and insecure connection.
-authority	Value to be used as the :authority pseudo-header. Only works if -insecure is used.
```
Breaking API changes with regards to `WithCertificate()`.
Adds new API functions for additional options.

Fix TLS credential options

---

cmd/ghz/config.go
cmd/ghz/main.go
runner/data.go
runner/options.go
runner/requester.go
testdata/config.json
testdata/config4.toml
www/docs/options.md

Add stream interval `-si` duration argument as a wait interval between sends of individual messages in client streaming and bidi streaming calls.
For example 
```
...
-call helloworld.Greeter.SayHelloBidi \
-d '[{"name": "Bob Smith"},{"name": "Bob 2"},{"name": "Bob 3"},{"name": "Bob Smith4"},{"name": "Bob Smith5"},{"name": "Bob Smith 6"},{"name": "Bob Smith 7"}]' \
-name 'Greeter SayHello' \
-si 500ms \
...
```
will cause the stream sends for client streaming and bidi streaming calls to be spread by 100 ms.

Add stream interval

---

Makefile
cmd/ghz-web/main.go
cmd/ghz/main.go
go.mod
go.sum
internal/common.go
printer/printer.go
runner/requester.go
web/database/database.go
web/router/router.go

This PR does a few things:
- Get ghz compliant with errcheck by propagating all errors, and documenting those that are purposefully ignored.
- Remove all panics.
- Remove all calls to the `log` package. Having a library log with the global stdlib logger makes it not possible for users to do logging in their own way.
- Remove all calls outside of `cmd/` to `fmt.Print*` for the same reason.
- Add TODOS in the `Requester` where errors should be handled.
- Do some locking in the `Requester`. Probably better to do some more extensive connection management in the future, but this is a start.
- Other minor cleanups.
- My editor removes whitespace, so a lot of that done.
Note this adds calls to https://godoc.org/go.uber.org/multierr#Append, which is a super simple library to handle having …

Get ghz compliant with errcheck

---

printer/printer.go

@bojand please review
---
It would be great to indicate a possible `format string` type for users.
Otherwise, users should look into the codebase and see the supported formats.
https://godoc.org/github.com/bojand/ghz/printer
Of course, you can guess them from CLI usage, but I think it is different and should be documented in the codebase as well.

Add supported format to printer.Print

---

printer/printer.go

This PR fixes #126 by using `fmt.Fprint` instead of `fmt.Fprintf` when printing ghz's output.

Use Fprint instead of Fprintf to fix #126

---

runner/call_template_data.go
runner/call_template_data_test.go
www/docs/calldata.md

Add TimestampUnixNano to call data as timestamp of the call as unix time in nanoseconds. Fixes #141.

Add Unix Nanosecond timestamp. Fixes #141.

---

runner/reporter.go
runner/reporter_test.go

Use [nearest rank](https://en.wikipedia.org/wiki/Percentile#The_nearest-rank_method) method to calculate percentiles. Fixes #215.

Percentile Latencies Fix

---

runner/call_template_data.go
runner/call_template_data_test.go
runner/options.go
runner/worker.go
www/docs/calldata.md

Adds template functions:
`newUUID` - Generates a new UUID for each invocation.
`randomString` - Generates a new random string for each incovation. Accepts a length parameter. If the argument is `<= 0` then a ranom string is generated with a random length between length of `2` and `16`.
Example usage with data:
```sh
-d '{"order_id":"{{newUUID}}", "item_id":"{{newUUID}}", "sku":"{{randomString 8 }}", "product_name":"{{ranomdString 0}}"}'
```
Would result in data with JSON representation:
```json
{
"order_id": "3974e7b3-5946-4df5-bed3-8c3dc9a0be19",
"item_id": "cd9c2604-cd9b-43a8-9cbb-d1ad26ca93a4",
"sku": "HlFTAxcm",
"product_name": "xg3NEC"
}
```
Also adds `WithTemplateFuncs()` API option.
Addresses #213.

Add template functions

---

cmd/ghz/main.go
runner/options.go
runner/options_test.go
runner/run_test.go
testdata/config5.toml

- Use `LoadConfig` in API to properly read in config
- Perform correct test duration init and setup in package API functions instead of just in cli

Fix file config API options

---

runner/requester.go
runner/run.go

Per https://github.com/bojand/ghz/issues/223 this PR adds the ability to create a `runner.Requester` without having to call `runner.Run` which has the issue that it blocks when called.  
Being able to create and have direct access to the `runner.Requester` means that a user can setup differing ways of canceling runs beyond what is possible with `runner.Run` as they will have direct access to `runner.Requester.Stop(...)`.
A potential alternative to this is exposing a new option that takes a channel that can be used to listen for a cancel signal, although that seems like a bit more complicated approach than this.

Exposes runner.NewRequester publicly

---

web/ui/src/components/ReportList.jsx

This PR targets ghz-web (frontend).
It adds a column selector to the reports component. Also this allows to display the "name" field.
Resolves issue #220 
I think it might be good idea to persist the selection to the localStorage, thoughts?
Second, I hoped to include the tags as well, because I would want to use them for search. I use tags to include application parameters for the benchmark. But I couldn't find a way to fit the tags nicely into the table.

Column selector in reports

---

runner/options.go
runner/options_test.go
runner/reporter_test.go
runner/run.go

Related to #224, this also exposes `runner.newConfig` to be public in order to configure the runner from outside of the package. This also supports #223.

Exposes runner.newConfig publicly

---

runner/call_template_data.go
runner/call_template_data_test.go
runner/options.go
runner/options_test.go
runner/run_test.go
runner/worker.go

This PR adds the ability to supply a `changeFunc` function for every request to ensure we can randomize data.
Solves: https://github.com/bojand/ghz/issues/197
I am using this as an internal library, before adding more e.g. to the CLI as well as updating the documentation, I wanted to clarify whether this solution makes sense implementation wise and just have a discussion in general 👍

[feature] [option] adding a func as a option to randomize each request 

---

runner/options.go

fix: in NewConfig() set host and call only if not set via config options. fixes #237

Set host and call only if not set via config options

---

runner/options.go
runner/options_test.go
runner/requester.go

Adds the option to define a client side load balancer.
There are only 2 available balancers by default: pick_first and round_robin. Default is pick_first.
This option can be defined on the client and passed as an option e.g.
```go
. WithClientLoadBalancing("round_robin") // for default round robin instead of first value
```
fixes: https://github.com/bojand/ghz/issues/103
This PR uses an old grpc deprecated [option](https://github.com/grpc/grpc-go/issues/3003) because some clients are not up to date to use the newest experimental api and therefore don't even have that option.
Linting fails because of ^
```
Error: runner/requester.go:326:23: SA1019: grpc.WithBalancerName is deprecated: use WithDefaultServiceConfig and WithDisableServiceConfig instead.  Will be removed in a future 1.x …
```

[feature] add client side load balancing

---

runner/options.go
runner/requester.go
runner/run_test.go
runner/worker.go

Add API for providing a stream message.
```go
callCounter := 0
// ...
WithStreamMessageProvider(func(cd *CallData) (*dynamic.Message, error) {
protoMsg := &helloworld.HelloRequest{Name: cd.WorkerID + ": " + strconv.Itoa(callCounter)}
dynamicMsg, err := dynamic.AsDynamicMessage(protoMsg)
if err != nil {
return nil, err
}
callCounter++
if callCounter == 5 {
err = ErrLastMessage
}
return dynamicMsg, err
}),
```

add stream message provider api

---

www/docs/calldata.md

Fixes a documentation typo related to `randomString()`.

docs(randomString): Fix ranom -> random typo.

---

runner/calldata.go
runner/calldata_test.go

According to https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md#storing-binary-data-in-metadata -bin metadata is base64 encoded in gRPC, but it's not possible to represent binary values in json. This assumes that any -bin metadata header should be decoded as base64 before passed along to gRPC.

base64 decode binary metadata

---

protodesc/protodesc.go
runner/options.go
runner/requester.go

In environments where the ghz application has no access to the file system, users might need to embed the protoset binary into the source code and pass it to the runner directly. This PR adds this functionality.

Add support for passing Protoset Binary as runner option

---

printer/printer.go

Fix response time histogram padding in the CLI

---

go.mod
go.sum
protodesc/protodesc.go
protodesc/protodesc_test.go
testdata/optional.proto

Updates github.com/jhump/protoreflect to handle proto3 optional keyword.
Without it, it fails with:
`field has label LABEL_OPTIONAL, but proto3 must omit labels other than 'repeated'`
Fixes #310

Support optional keyword in proto3.

---

printer/prometheus.go
printer/prometheus_test.go

When exporting as Prometheus text exposition format, the "name" label was used twice. This resulted in Prometheus sampling error when serving the results via HTTP endpoint: 
> label name "name" is not unique: invalid sample

Fix duplicate name in Prometheus labels

---

cmd/ghz/main.go

To address issue https://github.com/bojand/ghz/issues/313 
Issue was supposed to be resolved here: https://github.com/bojand/ghz/commit/76c59b6e2abc06fa3c7f4b2bf7b44b9272ceb651
... But I was still getting the same error when building the latest master and running locally - e.g.
```
➜  dist git:(master) ✗ ./ghz --insecure \
--proto=usage_data_gateway.proto \
--call=UsageDataGateway.Ping \
--lb-strategy=round_robin \
localhost:6421
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x134edf2]
goroutine 1 [running]:
go.uber.org/zap.(*SugaredLogger).log(0x0, 0x1, {0x0, 0x0}, {0xc00053d9d0, 0x8, 0x5}, {0x0, 0x0, 0x0})
/Users/markusnotti/go/pkg/mod/go.uber.org/zap@v1.13.0/sugar.go:221 +0x52 …
```

fix lb strategy logging error

---

.golangci.yml
runner/requester.go

fix deprecated usage of grpc.WithBalancerName in runner/requester.go

---

www/docs/calldata.md
www/docs/load.md
www/docs/options.md

Fix spellings of "increasing",  "invocation"

Fix minor spelling error in www doc

---

.github/workflows/build.yaml
.github/workflows/release.yaml
.golangci.yml
cmd/ghz/main.go
runner/calldata.go
runner/calldata_test.go
runner/config.go
runner/data.go
runner/data_test.go
runner/options.go
runner/requester.go
runner/run_test.go
runner/worker.go
www/docs/calldata.md
www/docs/options.md

Adds two options in hope to resolve #340.
**`--disable-template-functions`**
Disable execution of template functions within call data and metadata. This can be useful for some performance improvements. Note that if template functions are used within data with this option set to `true`, it will result in an error. If `--disable-template-data` is set to `true` this is automatically also set to `true`.
**`--disable-template-data`**
Disable execution of templates within call data and metadata. This can be useful for some performance improvements. This automatically also sets `disable-template-functions` to `true`.

add disable-template-funcs and disable-template-data option

---

README.md

Since go 1.16, go install command is introduced
https://go.dev/ref/mod#go-install

chore: guide go install

---

printer/template.go
www/website/static/sample.html

The previous URL results in a `403`: `Package size exceeded the configured limit of 100 MB.`
Also, temporarily disabled the `valueFormatter` as it results in error for the referenced britecharts release.
For issue: 392

Temporarily change britecharts CDN URL

---

runner/worker.go

cc https://github.com/bojand/ghz/issues/247
cc https://github.com/bojand/ghz/pull/322
EDIT: 
This enables us to **chain** `ghz` calls and thus set up load testing scenarios.
Here's an example usage:
```bash
req_books=$(mktemp)
rep_books=$(mktemp)
req_gets=$(mktemp)
rep_gets=$(mktemp)
P "Booking $TOTAL IPs..."
source="$(printf '{"privateNetworkId":"%s"}' "$PRIVATE_NETWORK_ID")"
jq \
--arg PROJECT_ID "$PROJECT_ID" \
--argjson tags "$TAGS" \
--argjson TOTAL "$TOTAL" \
--argjson source "$source" \
-nR '[range($TOTAL) | {projectId:$PROJECT_ID, tags:$tags, source:$source, resource:{id:input, type:"instance_server"}}]' \
< <(for ((i=0; i<TOTAL; i++)); do uuidgen ; done) \
>"$req_books"
DEBUG="$rep_books" RPS=10 load \
--proto api.proto \
--call v1.Api.BookIP \
--data-file "$req_books"
cat …
```

feat: redo input/response encoding for easy parsing

---

go.mod
go.sum

An older version of `protoreflect` imported `google.golang.org/grpc/test/grpc_testing` directly, instead of generating it or directly using it from `google.golang.org/grpc/interop/grpc_testing`. `google.golang.org/grpc` has removed it in the latest version (v1.55.0).
Unfortunately this makes old versions of `protoreflect` and therefore `ghz` incompatible with `google.golang.org/grpc` v1.55.0. Upgrading protoreflect would solve the issue.
I ran the tests locally, but there's two that are failing (`TestRunClientStreaming/with_stream_cancel` and `TestRunBidi/with_stream_cancel`). They are also failing on `master` for me, so maybe it's not important, but I thought i should mention it.
(There's also a linting error when I run the linter, from preexisting code. I can fix it also if you would …

Upgrade protoreflect from 1.9.0 to 1.15.1

---

runner/calldata.go
runner/calldata_test.go

Fix concurrency unsafety error of rand.Intn.

---

runner/data.go
runner/options.go
runner/requester.go
runner/worker.go

Adds an new option `WithStreamInterceptorProviderFunc` where a StreamInterceptorProviderFunc can be specified. With this option a new Stream Interceptor will be created for each new stream created.  The Stream Interceptor's Send and Recv functions will be called when a message is sent or received. Unlike the `StreamRecvMsgInterceptFunc` and `StreamMessageProviderFunc`, the StreamInterceptor can keep state that both Send and Recv functions may need access to.
Here is an example of how to use the Stream Interceptor:
`
type ABCStreamInterceptor struct {
MsgRcvCount  int
MsgSendCount int
MsgChan 	 chan int
}
func (s *ABCStreamInterceptor) Send(callData *CallData) (*dynamic.Message, error) {
defer func() { s.MsgSendCount++ }()
switch s.MsgSendCount {
case 0:
return …

Adds a stream interceptor to keep state between the send and receive calls
